# Generated for Reparos SJC Corporate API R1.
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="AvailabilitySnapshot", fields=[("workspace_id", models.CharField(max_length=80, primary_key=True, serialize=False)), ("windows", models.JSONField(blank=True, default=list)), ("version", models.PositiveIntegerField(default=1)), ("updated_at", models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name="Organization", fields=[("id", models.CharField(max_length=64, primary_key=True, serialize=False)), ("slug", models.SlugField(max_length=80, unique=True)), ("name", models.CharField(max_length=160)), ("display_name", models.CharField(max_length=160)), ("demo", models.BooleanField(default=False)), ("active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True))], options={"ordering": ["display_name"]}),
        migrations.CreateModel(name="PartnerMembership", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("role", models.CharField(choices=[("manager", "Gestor"), ("requester", "Solicitante"), ("viewer", "Consulta")], default="requester", max_length=24)), ("active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="corporate.organization")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="corporate_memberships", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="ServiceRequest", fields=[("id", models.CharField(max_length=80, primary_key=True, serialize=False)), ("external_request_id", models.CharField(max_length=120)), ("workspace_id", models.CharField(blank=True, default="", max_length=80)), ("location", models.JSONField(blank=True, default=dict)), ("requester", models.JSONField(blank=True, default=dict)), ("category", models.CharField(blank=True, default="Reparos", max_length=120)), ("priority", models.CharField(blank=True, default="Normal", max_length=40)), ("description", models.TextField(blank=True, default="")), ("attachments", models.JSONField(blank=True, default=list)), ("status", models.CharField(choices=[("new", "Novo"), ("reviewing", "Em análise"), ("waiting_information", "Aguardando informação"), ("quote_sent", "Orçamento enviado"), ("quote_approved", "Orçamento aprovado"), ("waiting_schedule", "Aguardando agendamento"), ("schedule_requested", "Horário solicitado"), ("scheduled", "Agendado"), ("in_service", "Em atendimento"), ("completed", "Concluído"), ("rejected", "Recusado"), ("cancelled", "Cancelado")], default="new", max_length=40)), ("client_decision", models.CharField(blank=True, default="", max_length=40)), ("provider_local_id", models.CharField(blank=True, default="", max_length=80)), ("quote", models.JSONField(blank=True, null=True)), ("proposed_windows", models.JSONField(blank=True, default=list)), ("schedule_request", models.JSONField(blank=True, null=True)), ("appointment", models.JSONField(blank=True, null=True)), ("server_version", models.PositiveIntegerField(default=1)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="service_requests", to="corporate.organization"))], options={"ordering": ["-updated_at"]}),
        migrations.AddConstraint(model_name="partnermembership", constraint=models.UniqueConstraint(fields=("user", "organization"), name="uniq_partner_membership")),
        migrations.AddConstraint(model_name="servicerequest", constraint=models.UniqueConstraint(fields=("organization", "external_request_id"), name="uniq_org_external_request")),
        migrations.AddIndex(model_name="servicerequest", index=models.Index(fields=["workspace_id", "updated_at"], name="corporate_s_workspa_d4f939_idx")),
        migrations.AddIndex(model_name="servicerequest", index=models.Index(fields=["organization", "status"], name="corporate_s_organiz_2d6823_idx")),
    ]
